config/routes.rb
SampleApp::Application.routes.draw do
  get "microposts/_micropost"
  get "users/new"
  get "staticpages/home"
  get "staticpages/help"
  get "staticpages/about"
  get "staticpages/contact"

  root to: 'staticpages#home'
  resources :users
  resources :staticpages
  resources :sessions, only: [:new, :create, :destroy]
  get '/signup'=> 'users#new'
  get '/signin'=> 'sessions#new'
  get '/signout'=> 'sessions#destroy', via: :delete
  get '/help'=> 'staticpages#help'
  get  '/about'=> 'staticpages#about'
  get '/contact'=> 'staticpages#contact'
  get '/show'=>'users#show'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
attr_accessor :content
belongs_to : user
validates :content, presence: true, length: { maximum: 140 }
validates :user_id, presence: true
default_scope order: 'microposts.created at DESC'

end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :name, :email,  :password, :password_confirmation
#has_secure_password
has_many :microposts,dependent: :destroy
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
 

  validates :name, presence: true , length: { maximum: 50 }
  # validates :email, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  uniqueness: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

 private
  def create_remember_token
    self.remember_token=SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  def _micropost
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user= User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
      else
      flash.now[:error] = 'Invalid email/password combination' 
      render 'new'
    end
  end
  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController
  	def home
  	end

  	def help
  	end

	def about
	end

	def contact
	end

	def show
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#before_filter :signed_in_user, only: [:index, :edit, :update, :destroy]
#before_filter :correct_user, only: [:edit, :update]



  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
@microposts = @user.microposts.paginate(page: params[:page])

  end
  def index
    @users = User.paginate(page: params[:page])
  end
  def create
   # @user=User.new(params[:user])
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
      else
render 'new'
    end
  end


  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def edit
    @user = User.find(params[:id])
 end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params.require(:user).permit(:name, :email,:password, :password_confirmation))
flash[:success] = "Profile updated"
sign_in @user
redirect_to @user
 else
render 'edit'
    end
  end
#def destroy
#User.find(params[:id]).destroy
#flash[:success]="User destroyed"
#redirect_to users_path
#end
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
# Returns the full title on a per-page basis.
#def full title(page title)
	#base title = "Ruby on Rails Tutorial Sample App"
	#if page title.empty?
         # base title
       #else
       # "#{base title} | #{page title}"
       # end
      # end
     end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token]= user.remember_token
    self.current_user = user
    end
  def signed_in?
    !current_user.nil?
    end
  
def current_user
@current_user ||= User.find_by_remember_token(cookies[:remember_token])
end
def current_user?(user)
user == current_user
end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  def store_location
    session[:return_to] = request.fullpath
  end
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user,options = {size:50})
   if user.email.present?
      gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatars/#{gravatar_id}.png"
      image_tag(gravatar_url, alt: user.name, class: "gravatar")
   end
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
     <!-- <li><%= link_to "About",'#'  %></li>
      <li><%= link_to "contact",'#'  %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>-->


<li><%= link_to "About", about_path  %></li>
      <li><%= link_to "contact",contact_path  %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>

    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <!--<%= link_to "sample app", '#', id: "logo"%>-->
      <%= link_to "sample app", root_path,id: "logo" %>
      <nav>
	<ul class="nav pull-right">
	  <!--<li><%= link_to "Home", '#' %></li>
	      <li><%= link_to "Help", '#' %>
	      <li><%= link_to "Sign in", '#' %>-->

	  <li><%= link_to "Home", root_path %></li>
	  <li><%= link_to "Help", help_path %>
	 <li><%= link_to "Sign in", '#' %>
	
	   <% if signed_in? %>
	  <li><%= link_to "Users",users_path %></li>
	  <li id="fat-menu" class="dropdown">
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	      Account <b class="caret"></b>
	    </a>
	    <ul class="dropdown-menu">
	      <li><%= link_to "Profile", current_user %></li>
	      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	      <li class="divider"></li>
	  </li>
	  <%= link_to "Sign out", signout_path, method: "delete" %>
	  </li>
	  </ul>
	  </li>
	  <% else %>
	  <li><%= link_to "Sign in", signin_path %></li>
	  <% end %>
	</ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby on Rails Tutorial Sample App | <%= yield(:title) %></title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <header class="navbar navbar-fixed-top">
      <div class="navbar-inner">
	<div class="container">

	  <%= flash.each do |key,value| %>
	  <div class="alert alert-<%= key %>"><%= value %></div>
	  <% end %>


	  <%= link_to "sample app", '#', id: "logo" %>
	  <nav>
	    <ul class="nav pull-right">
	      <li><%= link_to "Home",'#' %></li>

	      <li><%= link_to "Help",'#' %></li>
	      <li><%= link_to "Sign in", '#' %></li>
	    </ul>
	  </nav>
	</div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li>
<span class="content"><%= micropost.content %></span>
<span class="timestamp">
Posted <%= time_ago_in_words(micropost.created at) %> ago.
</span>
</li>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-error">
    The form contains <%= pluralize(@user.errors.count,"error") %>
    </div>
  <ul>
    <%= @user.errors.full_messages.each do|msg| %>
    <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/staticpages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
is a project to make a book and screencasts to teach web development
with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
is the sample application for the tutorial.
</p>

app/views/staticpages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
Contact Ruby on Rails Tutorial about the sample app at the
<a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/staticpages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
Get help on the Ruby on Rails Tutorial at the
<a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
To get help on this sample app, see the
<a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/staticpages/home.html.erb
<div class="center hero-unit">

<% provide(:title, 'Home') %>
<h1> Sample App</h1>
<p>
This is the home page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</p>
<!--<%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>-->
<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

</div>



<%= link_to image_tag("/assets/index.jpeg", alt: ""), 'http://rubyonrails.org/' %>

app/views/users/_user.html.erb
<li>
<%= gravatar_for user, size: 52 %>
<%= link_to user.name, user %>
<% if current_user.admin? && !current_user?(user) %>
| <%= link_to "delete", user, method: :delete, confirm: "You sure?" %>
<% end %>


</li>

app/views/users/edit.html.erb
<form action="/users/1" class="edit_user" id="edit_user_1" method="post">
<input name="_method" type="hidden" value="put" />

<% provide(:title, "Edit user") %><br><br><br>
<h1>Update your profile</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>
    <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
    <%= gravatar_for @user %><br>
  <center>  <a href="http://gravatar.com/emails">change</a></center>
  </div>
</div>
</form>

app/views/users/index.html.erb
<% provide(:title, 'All users') %><br><br>
<h1>All users</h1>
<%= will_paginate %>
<ul class="users">
<%= render @users %>

 <!-- <% @users.each do |user| %>-->
 <!-- <li>
    <%= gravatar_for user, size: 52 %>
    <%= link_to user.name, user %>
  </li>
  <% end %>-->
</ul>
<%= will_paginate %>



 

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %><br><br>
<h1>Sign up</h1>
<!--<p>Find me in app/views/users/new.html.erb</p>-->

<!--<div class ="row">
  <div class="span6 offset3">
    <%= form_for(@user)  do |f| %>
 <%= render 'shared/error_messages' %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    
    <%= f.submit "Create my account ", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>-->

<form accept-charset="UTF-8" action="/users" class="new_user"
      id="new_user" method="post">
  <%= render 'shared/error_messages' %>

  <label for="user_name">Name</label>
  <input id="user_name" name="user[name]" size="10" type="text" />

  <label for="user_email">Email</label>
  <input id="user_email" name="user[email]" size="10" type="text" />

  <label for="user_password">Password</label>
  <input id="user_password" name="user[password]" size="10" type="password" />

 <label for="user_password_confirmation">Confirmation</label>
 <input id="user_password_confirmation"
		 name="user[password_confirmation]" size="10" type="password" />

  <input class="btn btn-large btn-primary" name="commit" type="submit"
	 value="Create my account" />
</form>

app/views/users/show.html.erb
<% provide(:title, @user.name) %><br><br>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
	<%= gravatar_for @user %>
	<!--<%= @user.name %>-->
      </h1>
    </section>
  </aside>
  <div class="span8">
    <% if @user.microposts.any? %>
    <h3>Microposts (<%= @user.microposts.count %>)</h3>
    <ol class="microposts">
      <%= render @microposts %>
    </ol>
    <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>